### PR TITLE
Added selection sort descending order JavaScript

### PR DESCRIPTION
**Pull request by haydenty**
Love this repo!

This PR:
Expands on issue #128 
#2 wasn't clear if any and all algorithms were welcomed. Not too many I saw that showed descending sort algorithms.

Happy Hacking!

### CODE REVIEW

**Comment by Thuva4** [comment]
Update Readme

**Comment by haydenty** [comment]
@Thuva4 theres already a thumbs up for javascript selection sort not sure how you want me to represent this.

**Comment by Thuva4** [comment]
@haydenty Create a new row for selection sort( descending order)

**Comment by haydenty** [comment]
I updated the readme with a new row for descending.

**Pull request merged**
