### PR TITLE
edit distance solution added

### PR DESCRIPTION
**Pull request by amankh99**
There are two versions of edit distance, one is of O(m*n) space complexity and other is of O(min(m,n)) space complexity where m,n are length of two strings. First file is O(m*n) space complexity and second is of O(m) space complexity. Backtracking is also added.

### CODE REVIEW

**Comment by amankh99** [comment]
Please consider it under Hacktoberfest label.

**Comment by amankh99** [comment]
@Thuva4 , please review it and suggest any changes if you find anything wrong.

**Comment by Thuva4** [comment]
@amankh99 Update the Readme :+1:

**Comment by amankh99** [comment]
@Thuva4 , please review the changes and suggest further changes.

**Pull request merged**
