### PR TITLE
Depth First Search in JavaScript

### PR DESCRIPTION
**Pull request by maaz93**

### CODE REVIEW

**Comment by Thuva4** [comment]
Add your name into the contributor list in CONTRIBUTING.md :+1:

**Comment by maaz93** [comment]
I'm still not able to clone the repo to my Windows machine. As of now, it's because of `cannot create directory at 'Dijkstra's /C++'`. I'll need to re-fork and re-submit a PR. Can I add my name in a separate/next PR because I'll get merge conflicts now?

**Comment by Thuva4** [comment]
@maaz93  Can you give me the special characters that we want to avoid in the folder/file names.

**Comment by maaz93** [comment]
@Thuva4 I'll try to compile the list and share on #241

**Pull request merged**
